# Generated by Django 3.2.12 on 2023-11-17 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=20)),
                ('image', models.FileField(default=None, upload_to='')),
                ('status', models.CharField(default='unblocked', max_length=20)),
                ('filter_status', models.CharField(default='unblocked', max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.register_tb')),
            ],
        ),
    ]
