# Generated by Django 3.2.12 on 2023-11-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0002_post_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_tb',
            name='status',
            field=models.CharField(default='public', max_length=20),
        ),
    ]
