# Generated by Django 3.2.12 on 2023-11-18 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0003_alter_post_tb_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='friend_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='none', max_length=20)),
                ('filter_status', models.CharField(default='none', max_length=20)),
                ('friend_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.register_tb')),
            ],
        ),
    ]
