# Generated by Django 3.2.12 on 2023-11-18 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0005_friend_tb_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='reply_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply', models.CharField(max_length=20)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.register_tb')),
            ],
        ),
        migrations.CreateModel(
            name='comment_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('comment', models.CharField(max_length=20)),
                ('commenter_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.register_tb')),
            ],
        ),
    ]
