# Generated by Django 3.2.12 on 2023-11-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0006_comment_tb_reply_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_tb',
            name='friend_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
