# Generated by Django 3.2.12 on 2023-11-18 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0007_alter_friend_tb_friend_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_tb',
            name='filter_status',
        ),
        migrations.RemoveField(
            model_name='friend_tb',
            name='status',
        ),
        migrations.AddField(
            model_name='friend_tb',
            name='request_from',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='friend_tb',
            name='requested_to',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
