# Generated by Django 3.2.12 on 2023-11-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0008_auto_20231118_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_tb',
            name='friend_user_name',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
