# Generated by Django 3.2.12 on 2023-11-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0010_alter_friend_tb_friend_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_tb',
            name='friend_user_name',
        ),
    ]
