# Generated by Django 3.2.12 on 2023-11-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0011_remove_friend_tb_friend_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_tb',
            name='friend_id',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='friend_tb',
            name='request_from',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_buddy.register_tb'),
        ),
    ]
