# Generated by Django 3.2.12 on 2023-11-18 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0012_auto_20231118_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend_tb',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
