# Generated by Django 3.2.12 on 2023-11-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0013_friend_tb_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_tb',
            name='friend_id',
        ),
        migrations.RemoveField(
            model_name='friend_tb',
            name='user_id',
        ),
    ]
