# Generated by Django 3.2.12 on 2023-11-27 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0014_auto_20231120_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment_tb',
            name='post_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_buddy.post_tb'),
        ),
        migrations.AddField(
            model_name='reply_tb',
            name='post_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_buddy.comment_tb'),
        ),
    ]
