# Generated by Django 3.2.12 on 2023-11-28 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0016_auto_20231127_0409'),
    ]

    operations = [
        migrations.CreateModel(
            name='likes_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_count', models.CharField(max_length=20)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.post_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.register_tb')),
            ],
        ),
    ]
