# Generated by Django 3.2.12 on 2023-11-29 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0017_likes_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes_tb',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
