# Generated by Django 3.2.12 on 2023-11-29 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0018_alter_likes_tb_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes_tb',
            name='user_id',
        ),
    ]
