# Generated by Django 3.2.12 on 2023-11-29 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0019_remove_likes_tb_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='liked_users_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.register_tb')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.likes_tb')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.post_tb')),
            ],
        ),
    ]
