# Generated by Django 3.2.12 on 2023-11-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0020_liked_users_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liked_users_tb',
            old_name='liked_user_id',
            new_name='user_id',
        ),
    ]
