# Generated by Django 3.2.12 on 2023-12-01 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0021_rename_liked_user_id_liked_users_tb_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='likes_tb',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_buddy.register_tb'),
        ),
        migrations.DeleteModel(
            name='liked_users_tb',
        ),
    ]
