# Generated by Django 3.2.12 on 2023-12-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0022_auto_20231201_1256'),
    ]

    operations = [
        migrations.CreateModel(
            name='total_likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_like', models.IntegerField()),
            ],
        ),
    ]
