# Generated by Django 3.2.12 on 2023-12-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0023_total_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='total_likes',
            name='post_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app_buddy.post_tb'),
        ),
    ]
