# Generated by Django 3.2.12 on 2023-12-02 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0024_total_likes_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_likes',
            name='post_id',
        ),
        migrations.AddField(
            model_name='post_tb',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post_tb',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='likes_tb',
        ),
        migrations.DeleteModel(
            name='total_likes',
        ),
    ]
