# Generated by Django 3.2.12 on 2023-12-02 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0025_auto_20231202_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='liked_by_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.register_tb')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.post_tb')),
            ],
        ),
    ]
