# Generated by Django 3.2.12 on 2023-12-02 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0026_liked_by_tb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liked_by_tb',
            old_name='liked_user_id',
            new_name='user_id',
        ),
    ]
