# Generated by Django 3.2.12 on 2023-12-03 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0027_rename_liked_user_id_liked_by_tb_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='notifications_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=20)),
                ('like', models.CharField(max_length=20)),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.post_tb')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_buddy.register_tb')),
            ],
        ),
    ]
