# Generated by Django 3.2.12 on 2023-12-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0028_notifications_tb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications_tb',
            name='comment',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='notifications_tb',
            name='like',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
