# Generated by Django 3.2.12 on 2023-12-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_buddy', '0029_auto_20231203_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications_tb',
            name='remarks',
            field=models.CharField(default='unseen', max_length=20),
        ),
    ]
